DIRS += src/

SOURCES += \
FillHistBase.C \
MTAEvent.C \
KazNeutronAnalysis.cpp \
NeutronEfficiencyAnalysis.C \
TPCEnergyTokeV.C \
MuEntrancePileupCorrection.C \
MusunNeutronAnalysis.C \
MusunNeutronHists.C \
MusunNeutronSTAnalysis.C \
MusunNeutronSTHists.C \
MusunNeutronBlockAnalysis.C \
TPCClusterAnalysis.C \
TPCPulseCompare.C \
TPCClusterHists.C \
TPCMiniStopHists.C \
TPCRawPulseClusterAnalysis.C \
TPCRawPulseClusterHists.C \
TPCRawMiniComparison.C \
TPCTOTPulseClusterAnalysis.C \
TPCTOTPulseClusterHists.C \
TPCTOTStopHists.C \
TPCTOTRoadStopHists.C \
TPCTOTRoadStopThreshStopHists.C \
TPCTOTRoadStopThreshStopHistsReqEl.C \
TPCTOTTightRoadStopThreshStopHists.C \
TPCTOTRoadPDirStopHists.C \
TPCTOTCalibrationHists.C \
TPCUpstreamStopHists.C \
TPCTOTMiniComparison.C \
TPCTOTRoadTrackAnalysis.C \
TPCFusionAnalysis.C \
TPCPTAnalysis.C \
LifetimeVsEntranceDetectors.C \
LifetimeVsMCTruth.C \
LifetimeHists.C \
ePCOnlyHists.C \
NoFusionAnalysis.C \
MCLifetimeHists.C \
XRayMuStopAnalysis.C \
CaptureRecoilAnalysis.C \
MCTruthCheck.C \
TPCmuPC_Correlation.C \
TPCmuPC_CorrelationHists.C \
TPCUpstreamAnalysis.C \
TPCUpstreamHists.C \
TPCUpstreamEnergies.C \
LifetimeVsImpactPar.C \
LifetimeVsXYZ.C \
LifetimeVsStopEnergy.C \
ElectronTomographyAnalysis.C \
uiuc_utils.cpp \
uiuc_tree_utils.C \
main.cpp \
TBasicEventDisplay.cpp \
TTrackBasicEventDisplay.cpp \
TTrackEventDisplay.cpp \
TMichaelsMTAEventDisplay.cpp \
TBasicShapes.cpp \
TTimeColors.cpp \
TSpecialEventFrame.cpp \
MTAGlobals.C \
TTPCCalibration.cpp \
TTPCMuonTrack.cpp \
TTPCProjectionMuonTrack.cpp \
TTPCWaveform.cpp \
TTPCWaveformDisplay.cpp \
TTPCPadLayoutDisplay.cpp \
TTPCFusionDisplay.cpp \
TeSCIslandDisplay.cpp \
TTPCDisplayPad.cpp \
TTPCMTAGaussPulseDataRetriever.cpp \
TTPCMTAMiniPulseDataRetriever.cpp \
TTPCMTARawPulseDataRetriever.cpp \
TTPCPulseDataRetrieverMTA.cpp \
TTPCTrackDataRetrieverMTA.cpp \
TMuEntranceDataRetriever.cpp \
TMuEntranceDataRetrieverMTA.cpp \
TMCDataRetrieverMTA.cpp \
TMCDataRetriever.cpp \
TMuonEvent.cpp \
TMuonEventDataRetriever.cpp \
TTPCIslandDataRetriever.cpp \
TTPCIslandDataRetrieverMTA.cpp \
TTPCEventProperties.cpp \
MuEPairTreeBuilder.C \
TPCUpstreamCalibration.C \
McResponseCalibration.C \
MichelElectronStudy.C \
webGLDisplay.C \
GlobalElectronGondOnlyLifetime.C \
GlobalElectronAnalysis.C \
GondolaOnlyAnalysis.C \
ElectronTrackAnalysis.C \
ElectronDisplayEM.C \
TGondolaCluster.cpp \
TGlobalElectronTrack.cpp \
TElectronTrack.cpp \
TGlobalElectronTrack_SingleTube.cpp \
TePCCluster.cpp \
TePCHit.cpp \
DelayedEventTreeBuilder.C \
DelayedEvent.C \
THistogramCollection.cpp \
TTPCPulseClusterHistograms.cpp \
TTPCMuonTrackHistograms.cpp \
TLifetimeHistograms.cpp \
TLifetimeHistograms_ElectronBG.cpp \
TLifetimeHistograms_Tree.cpp \
TLifetimeHistograms_ePC.cpp \
GondolaClusterHistograms.C \
ElectronBackgroundAnalysis.C \
ClockBackgroundAnalysis.C \
TPCRoadAndClusterStopComparison.C \
GondolaWFDPedestalAnalysis.C \
TTPCPadPattern.cpp \
TPCTrackPatternAnalysis.C \
GlobalElectronTracksLifetimeSingleTube.C \
GlobalElectronTracksLifetime.C \
EntranceEfficiencyAnalysis.C \
EntranceEfficiencyAnalysisRR.C \
TPCSinglePadAnalysis.C \
TTPCMCStopComparison.cpp \
TTPCMCWallStopComparison.cpp \
TPCMCStopCompare.C \
TPCMCWallStops.C \
MuEntranceChecks.C \
MuSCAnalysis.C \
GondolaTwoFoldAnalysis.C \
MuSCDTScan.C \
TLifetime_MuSCDTScanHistograms.cpp \
TLifetimePileupHistograms.cpp \
TLifetime_ElectronBackgroundHistograms.cpp \
MuonTimeSmear.C \
EntranceEfficiencyLifetime.C \
TPCSkimAnalysis.C \
TPCMCElectronSkimAnalysis.C \
TPCFusionStopHists.C \
TPCStopDistAnalysis.C \
TTPCStopDist.cpp \
ElectronBackgroundLifetime.C \
BeamElectronAnalysis.C \
TPCDelayedFusionStopAnalysis.C \
DelayedEventAnalysis.C \
TTPCDelayedEventHistograms.cpp \
SmearAllMuonTimes.C \
CosmicsHists.C \
LifetimeEventTreeBuilder.C \
LifetimeEvent.C \
stopDistPair.C \
stopDistPairTreeBuilder.C \
MuCLPileupCorrection.C \
ExtendedPileupCorrection.C \
GondolaClustering.C \
ElectronAnalysisComparison.C \
TPCOffsetCalib.C \
TPCPulseRecalibration.cpp 

HEADERS += \
TMusunEvent.h \
FillHistBase.h \
MTAEvent.h \
KazNeutronAnalysis.h \
NeutronEfficiencyAnalysis.h \
TPCEnergyTokeV.h \
MuEntrancePileupCorrection.h \
MusunNeutronAnalysis.h \
MusunNeutronHists.h \
MusunNeutronSTAnalysis.h \
MusunNeutronSTHists.h \
MusunNeutronBlockAnalysis.h \
TPCClusterAnalysis.h \
TPCPulseCompare.h \
TPCClusterHists.h \
TPCMiniStopHists.h \
TPCRawPulseClusterAnalysis.h \
TPCRawPulseClusterHists.h \
TPCRawMiniComparison.h \
TPCTOTPulseClusterAnalysis.h \
TPCTOTPulseClusterHists.h \
TPCTOTStopHists.h \
TPCTOTRoadStopHists.h \
TPCTOTRoadStopThreshStopHists.h \
TPCTOTRoadStopThreshStopHistsReqEl.h \
TPCTOTTightRoadStopThreshStopHists.h \
TPCTOTRoadPDirStopHists.h \
TPCTOTCalibrationHists.h \
TPCUpstreamStopHists.h \
TPCTOTMiniComparison.h \
TPCTOTRoadTrackAnalysis.h \
TPCFusionAnalysis.h \
NoFusionAnalysis.h \
TPCPTAnalysis.h \
LifetimeVsEntranceDetectors.h \
LifetimeVsMCTruth.h \
LifetimeHists.h \
ePCOnlyHists.h \
MCLifetimeHists.h \
BasicShapes.h \
XRayMuStopAnalysis.h \
CaptureRecoilAnalysis.h \
MCTruthCheck.h \
TPCmuPC_Correlation.h \
TPCmuPC_CorrelationHists.h \
TPCUpstreamAnalysis.h \
TPCUpstreamHists.h \
TPCUpstreamEnergies.h \
LifetimeVsImpactPar.h \
LifetimeVsXYZ.h \
LifetimeVsStopEnergy.h \
ElectronTomographyAnalysis.h \
uiuc_utils.h \
uiuc_tree_utils.h \
TBasicEventDisplay.h \
TTrackBasicEventDisplay.h \
TTrackEventDisplay.h \
TMichaelsMTAEventDisplay.h \
TBasicShapes.h \
TTimeColors.h \
TSpecialEventFrame.h \
MTAGlobals.h \
TTPCCalibration.h \
TTPCMuonTrack.h \
TTPCProjectionMuonTrack.h \
TTPCWaveform.h \
TTPCWaveformDisplay.h \
TTPCPadLayoutDisplay.h \
TeSCIslandDisplay.h \
TTPCDisplayPad.h \
TTimeWindow.h \
TTPCMTAGaussPulseDataRetriever.h \
TTPCMTAMiniPulseDataRetriever.h \
TTPCMTARawPulseDataRetriever.h \
TTPCPulseDataRetrieverMTA.h \
TTPCPulseDataRetriever.h \
TTPCTrackDataRetrieverMTA.h \
TTPCTrackDataRetriever.h \
TMuEntranceDataRetriever.h \
TMCDataRetrieverMTA.h \
TMCDataRetriever.h \
TMuonEvent.h \
TMuonEventDataRetriever.h \
TTPCIslandDataRetriever.h \
TTPCIslandDataRetrieverMTA.h \
TTPCEventProperties.h \
MuEPairTreeBuilder.h \
MuEPair.h \
TPCUpstreamCalibration.h \
McResponseCalibration.h \
MichelElectronStudy.h \
webGLDisplay.h \
GlobalElectronGondOnlyLifetime.h \
GlobalElectronAnalysis.h \
GondloaOnlyAnalysis.h \
ElectronTrackAnalysis.h \
ElectronDisplayEM.h \
TGondolaCluster.h \
TePCCluster.h \
TePCHit.h \
TGlobalElectronTrack.h \
TGlobalElectronTrack_SingleTube.h \
TElectronTrack.h \
DelayedEventTreeBuilder.h \
DelayedEvent.h \
THistogramCollection.h \
TTPCPulseClusterHistograms.h \
TTPCMuonTrackHistograms.h \
TLifetimeHistograms.h \
TLifetimeHistograms_ElectronBG.h \
TLifetimeHistograms_Tree.h \
TLifetimeHistograms_ePC.h \
GondolaClusterHistograms.h \
ElectronBackgroundAnalysis.h \
ClockBackgroundAnalysis.h \
TPCRoadAndClusterStopComparison.h \
GondolaWFDPedestalAnalysis.h \
TTPCPadPattern.h \
TPCTrackPatternAnalysis.h \
GlobalElectronTracksLifetimeSingleTube.h \
GlobalElectronTracksLifetime.h \
EntranceEfficiencyAnalysis.h \
EntranceEfficiencyAnalysisRR.h \
TPCSinglePadAnalysis.h \
TTPCMCStopComparison.h \
TTPCMCWallStopComparison.h \
TPCMCStopCompare.h \
TPCMCWallStops.h \
MuEntranceChecks.h \
MuSCAnalysis.h \
GondolaTwoFoldAnalysis.h \
MuSCDTScan.h \
TLifetime_MuSCDTScanHistograms.h \
TLifetimePileupHistograms.h \
TLifetime_ElectronBackgroundHistograms.h \
MuonTimeSmear.h \
EntranceEfficiencyLifetime.h \
TPCSkimAnalysis.h \
TPCMCElectronSkimAnalysis.h \
TPCFusionStopHists.h \
TPCStopDistAnalysis.h \
TTPCStopDist.h \
ElectronBackgroundLifetime.h \
BeamElectronAnalysis.h \
TPCDelayedFusionStopAnalysis.h \
DelayedEventAnalysis.h \
TTPCDelayedEventHistograms.h \
SmearAllMuonTimes.h \
CosmicsHists.h \
LifetimeEventTreeBuilder.h \
LifetimeEvent.h \
stopDistPair.h \
stopDistPairTreeBuilder.h \
MuCLPileupCorrection.h \
ExtendedPileupCorrection.h \
GondolaClustering.h \
ElectronAnalysisComparison.h \
TPCOffsetCalib.h \
TPCPulseRecalibration.h
